### ISSUE TITLE
Open-Frame 1 support, building questions

### ISSUE THREAD

**Issue by Soundtoxin** [JonnyHaystack/HayBox#28]
For use on an Open-Frame1 (Pi Pico + Open-Frame1 PCB), would I just build the Pico version? How does it know how many buttons I have and such?
I'm also curious if it's possible to build this without VSCode/VSCodium, both because I'd rather not install an extra editor I don't want to use, and because Guix dosen't have VSCodium packaged, so it would be difficult to get it on my main PC. If necessary I'll either have a trusted friend build the firmware for me or have to use a different computer for setup I suppose.
Is there a reason that prebuilt firmware is not provided at all, by the way? I see in the screenshots in the readme that you can build for a few different controllers, but then I wonder why you couldn't put the firmware for them all in the releases. Maybe you expect people to tweak some things before building, but if any of the builds would be usable by default, I think it'd be worth providing binaries.

BTW, thank you very much for releasing this project as free (as in freedom) software.

**Comment by JonnyHaystack** [comment]
You don't actually need VS Code, no. You can just use the PlatformIO CLI to the same effect. Prebuilt binaries are provided for the Pico, but there were no changes that affected Pico in the latest release so I didn't copy the file for that one. In the future I do plan to set up automated builds for each environment, but last time I tried I didn't quite manage to get it working how I want it to.
