### ISSUE TITLE
[Pico] Taunt / D-pad

### ISSUE THREAD

**Issue by Soundtoxin** [JonnyHaystack/HayBox#37]
I'm playing Rivals of Aether and the tutorials requires you to hit a taunt button to repeat the instructions. Is that possible with HayBox? I mashed around a bit wondering if one of the modifier buttons would turn something into a d-pad, but I didn't figure anything out.

**Comment by JonnyHaystack** [comment]
Hold Mod X + Mod Y and C-Stick turns into D-Pad, same as B0XX standard
