### ISSUE TITLE
two mod_x buttons?

### ISSUE THREAD

**Issue by Tree52** [JonnyHaystack/HayBox#40]
Want two mod_x buttons but only one of them works :( Maybe there's a way and I'm just dumb.

![image](https://user-images.githubusercontent.com/108751195/218143185-3314c228-a6a8-49e6-b5a1-eaf0d2b6e9f3.png)

**Comment by AtomToast** [comment]
There can only be one of each button in your layout. I also had to ask Haystack for help on this one. 
So the only way is to create more modifiers. Take a look at this commit from my personal fork to see how you could possibly do this https://github.com/AtomToast/HayBox/commit/b06eebd24c311646525b4ed497f828d2a9dcc4fd

**Comment by Tree52** [comment]
Thanks :D I got it working. Making bool mod_x_pressed is smart, rather than just doing mod_x || mod_x1 everywhere like I probably would have done, haha. Closing the issue.

**Comment by JonnyHaystack** [comment]
> Thanks :D I got it working. Making bool mod_x_pressed is smart, rather than just doing mod_x || mod_x1 everywhere like I probably would have done, haha. Closing the issue.

You could also just do `inputs.mod_x = inputs.mod_x || inputs.mod_x1` if you want to keep changes minimal and you want them to be treated exactly the same.
