### ISSUE TITLE
twoIP Edge Case Clarification

### ISSUE THREAD

**Issue by trshfgc** [JonnyHaystack/HayBox#53]
I was looking through this firmware's SOCD resolution and making some modification and noticed that the twoIP function seems to output a neutral if both socd_state.was_dir1 and socd_state.was_dir2 are false and both of the SOCD inputs are true. Is this intended behavior?

**Comment by JonnyHaystack** [comment]
Yeah that's how it's supposed to work. I don't see how else you'd resolve that. It only happens if you press opposing directions on the same poll, and in that situation you can't really say which one should have priority over the other.
