### ISSUE TITLE
'home' button mapping on pico (GPIO11) is the same pin as the rumble pin on Arte's rectangle FW. [Pico]

### ISSUE THREAD

**Issue by SergioPDhe** [JonnyHaystack/HayBox#59]
Hello, Rumble Enjoyer Mr. Potatobread here.

One of my rumble-box users was experiencing some issues after switching to this FW from Arte's: Dpad-right seemed to always be held down on both PC and console.
After some investigation, I found that the "home" button results in a Dpad-right output, and the pin 'home' is mapped to (GPIO11) is the same as the rumble signal pin on Arte's FW.

This is obviously not a life-or-death issue, and my friend here is likely the only person to ever experience this very specific issue - but I figured I would post it here in case people in the future had this problem or if there were plans to add rumble to this FW. 

For now I just changed 'home' to GPIO9 to solve the issue.

Cheers!

**Comment by JonnyHaystack** [comment]
Thanks for sharing. I don't think I'll change it though, because at this point there are a lot more people with select/home buttons than with rumble.
